svn checkout http://rdinnovation.onf.fr/svn/computreev6/ computreev6
svn checkout http://rdinnovation.onf.fr/svn/plugin-onf/dev_v6/ pluginonf
svn checkout http://rdinnovation.onf.fr/svn/plugin-mk/dev_v6/ pluginmk
svn checkout http://rdinnovation.onf.fr/svn/plugin-toolkit/dev_v6/ plugintoolkit
svn checkout http://rdinnovation.onf.fr/svn/segma/dev_v6/ pluginsegma
svn checkout http://rdinnovation.onf.fr/svn/plugin-generate/dev_v6/ plugingenerate
svn checkout http://rdinnovation.onf.fr/svn/plugin-onf-dev/dev_v6/ pluginonfdev
svn checkout http://rdinnovation.onf.fr/svn/plugin-ign-lif/dev_v6/ pluginignlif
svn checkout http://rdinnovation.onf.fr/svn/plugin-lvox/dev_v6/ pluginlvox
